# Generated by Django 4.2.20 on 2025-04-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OffsideDecision",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("file_name", models.CharField(db_column="filename", max_length=2048)),
                (
                    "algorithm_offside",
                    models.BooleanField(db_column="algorithm_offside"),
                ),
                (
                    "final_offside",
                    models.BooleanField(db_column="final_offside", null=True),
                ),
                ("time_uploaded", models.DateField(db_column="time_uploaded")),
                ("time_decided", models.DateField(db_column="time_decided", null=True)),
            ],
            options={
                "db_table": "offside_decision",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ObjectDetection",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "player_detections",
                    models.CharField(db_column="player_detections", max_length=2048),
                ),
                (
                    "keeper_detections",
                    models.CharField(db_column="keeper_detections", max_length=2048),
                ),
                (
                    "ball_detections",
                    models.CharField(db_column="ball_detections", max_length=2048),
                ),
                (
                    "ref_detections",
                    models.CharField(db_column="ref_detections", max_length=2048),
                ),
                (
                    "decision_id",
                    models.ForeignKey(
                        db_column="decision_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="frontend.offsidedecision",
                    ),
                ),
            ],
            options={
                "db_table": "object_detection",
                "managed": True,
            },
        ),
    ]
