# Generated by Django 4.2.20 on 2025-04-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectDetection",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("ball_xy", models.CharField(db_column="ball_xy", max_length=2048)),
                ("file_path", models.CharField(db_column="file_path", max_length=2048)),
                ("refs_xy", models.CharField(db_column="refs_xy", max_length=2048)),
                (
                    "players_xy",
                    models.CharField(db_column="players_xy", max_length=2048),
                ),
                (
                    "players_detections",
                    models.CharField(db_column="players_detections", max_length=2048),
                ),
            ],
            options={
                "db_table": "object_detection",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OffsideDecision",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "algorithm_decision",
                    models.CharField(
                        choices=[("onside", "Onside"), ("offside", "Offside")],
                        db_column="algorithm_decision",
                        max_length=10,
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[("onside", "Onside"), ("offside", "Offside")],
                        db_column="final_decision",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("time_uploaded", models.DateTimeField(db_column="time_uploaded")),
                (
                    "time_decided",
                    models.DateTimeField(db_column="time_decided", null=True),
                ),
                (
                    "detection_id",
                    models.ForeignKey(
                        db_column="detection_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="frontend.objectdetection",
                    ),
                ),
            ],
            options={
                "db_table": "offside_decision",
                "managed": True,
            },
        ),
    ]
