# Generated by Django 4.2.20 on 2025-04-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectDetection",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("ball_xy", models.TextField(db_column="ball_xy")),
                ("file_path", models.FileField(db_column="file_path", upload_to="")),
                ("refs_xy", models.TextField(db_column="refs_xy")),
                ("players_xy", models.TextField(db_column="players_xy")),
                (
                    "players_detections",
                    models.TextField(db_column="players_detections"),
                ),
            ],
            options={
                "db_table": "object_detection",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OffsideDecision",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "algorithm_decision",
                    models.CharField(
                        choices=[("onside", "Onside"), ("offside", "Offside")],
                        db_column="algorithm_decision",
                        max_length=10,
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[("onside", "Onside"), ("offside", "Offside")],
                        db_column="final_decision",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("time_uploaded", models.DateTimeField(db_column="time_uploaded")),
                (
                    "time_decided",
                    models.DateTimeField(db_column="time_decided", null=True),
                ),
                (
                    "detection_id",
                    models.ForeignKey(
                        db_column="detection_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="frontend.objectdetection",
                    ),
                ),
                (
                    "referee_id",
                    models.ForeignKey(
                        db_column="referee_id",
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "offside_decision",
                "managed": True,
            },
        ),
    ]
