# Generated by Django 4.2.20 on 2025-04-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_offsidedecision_referee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectdetection",
            name="ball_xy",
            field=models.CharField(db_column="ball_xy", max_length=4096),
        ),
        migrations.AlterField(
            model_name="objectdetection",
            name="file_path",
            field=models.CharField(db_column="file_path", max_length=4096),
        ),
        migrations.AlterField(
            model_name="objectdetection",
            name="players_detections",
            field=models.CharField(db_column="players_detections", max_length=4096),
        ),
        migrations.AlterField(
            model_name="objectdetection",
            name="players_xy",
            field=models.CharField(db_column="players_xy", max_length=4096),
        ),
        migrations.AlterField(
            model_name="objectdetection",
            name="refs_xy",
            field=models.CharField(db_column="refs_xy", max_length=4096),
        ),
    ]
